const ORACLE = {
    "Generic Roll": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
        17: "17",
        18: "18",
        19: "19",
        20: "20",
        21: "21",
        22: "22",
        23: "23",
        24: "24",
        25: "25",
        26: "26",
        27: "27",
        28: "28",
        29: "29",
        30: "30",
        31: "31",
        32: "32",
        33: "33",
        34: "34",
        35: "35",
        36: "36",
        37: "37",
        38: "38",
        39: "39",
        40: "40",
        41: "41",
        42: "42",
        43: "43",
        44: "44",
        45: "45",
        46: "46",
        47: "47",
        48: "48",
        49: "49",
        50: "50",
        51: "51",
        52: "52",
        53: "53",
        54: "54",
        55: "55",
        56: "56",
        57: "57",
        58: "58",
        59: "59",
        60: "60",
        61: "61",
        62: "62",
        63: "63",
        64: "64",
        65: "65",
        66: "66",
        67: "67",
        68: "68",
        69: "69",
        70: "70",
        71: "71",
        72: "72",
        73: "73",
        74: "74",
        75: "75",
        76: "76",
        77: "77",
        78: "78",
        79: "79",
        80: "80",
        81: "81",
        82: "82",
        83: "83",
        84: "84",
        85: "85",
        86: "86",
        87: "87",
        88: "88",
        89: "89",
        90: "90",
        91: "91",
        92: "92",
        93: "93",
        94: "94",
        95: "95",
        96: "96",
        97: "97",
        98: "98",
        99: "99",
        100: "100",
    },
    "DIVIDER1": null,
    "Almost Certain": {
        10: "No",
        100: "Yes",
    },
    "Likely": {
        25: "No",
        100: "Yes",
    },
    "50/50": {
        50: "No",
        100: "Yes",
    },
    "Unlikely": {
        75: "No",
        100: "Yes",
    },
    "Small Chance": {
        90: "No",
        100: "Yes",
    },
    "DIVIDER2": null,
    Action: {
        1: "Scheme",
        2: "Clash",
        3: "Weaken",
        4: "Initiate",
        5: "Create",
        6: "Swear",
        7: "Avenge",
        8: "Guard",
        9: "Defeat",
        10: "Control",
        11: "Break",
        12: "Risk",
        13: "Surrender",
        14: "Inspect",
        15: "Raid",
        16: "Evade",
        17: "Assault",
        18: "Deflect",
        19: "Threaten",
        20: "Attack",
        21: "Leave",
        22: "Preserve",
        23: "Manipulate",
        24: "Remove",
        25: "Eliminate",
        26: "Withdraw",
        27: "Abandon",
        28: "Investigate",
        29: "Hold",
        30: "Focus",
        31: "Uncover",
        32: "Breach",
        33: "Aid",
        34: "Uphold",
        35: "Falter",
        36: "Suppress",
        37: "Hunt",
        38: "Share",
        39: "Destroy",
        40: "Avoid",
        41: "Reject",
        42: "Demand",
        43: "Explore",
        44: "Bolster",
        45: "Seize",
        46: "Mourn",
        47: "Reveal",
        48: "Gather",
        49: "Defy",
        50: "Transform",
        51: "Persevere",
        52: "Serve",
        53: "Begin",
        54: "Move",
        55: "Coordinate",
        56: "Resist",
        57: "Await",
        58: "Impress",
        59: "Take",
        60: "Oppose",
        61: "Capture",
        62: "Overwhelm",
        63: "Challenge",
        64: "Acquire",
        65: "Protect",
        66: "Finish",
        67: "Strengthen",
        68: "Restore",
        69: "Advance",
        70: "Command",
        71: "Refuse",
        72: "Find",
        73: "Deliver",
        74: "Hide",
        75: "Fortify",
        76: "Betray",
        77: "Secure",
        78: "Arrive",
        79: "Affect",
        80: "Change",
        81: "Defend",
        82: "Debate",
        83: "Support",
        84: "Follow",
        85: "Construct",
        86: "Locate",
        87: "Endure",
        88: "Release",
        89: "Lose",
        90: "Reduce",
        91: "Escalate",
        92: "Distract",
        93: "Journey",
        94: "Escort",
        95: "Learn",
        96: "Communicate",
        97: "Depart",
        98: "Search",
        99: "Charge",
        100: "Summon",
    },
    Theme: {
        1: "Risk",
        2: "Ability",
        3: "Price",
        4: "Ally",
        5: "Battle",
        6: "Safety",
        7: "Survival",
        8: "Weapon",
        9: "Wound",
        10: "Shelter",
        11: "Leader",
        12: "Fear",
        13: "Time",
        14: "Duty",
        15: "Secret",
        16: "Innocence",
        17: "Renown",
        18: "Direction",
        19: "Death",
        20: "Honor",
        21: "Labor",
        22: "Solution",
        23: "Tool",
        24: "Balance",
        25: "Love",
        26: "Barrier",
        27: "Creation",
        28: "Decay",
        29: "Trade",
        30: "Bond",
        31: "Hope",
        32: "Superstition",
        33: "Peace",
        34: "Deception",
        35: "History",
        36: "World",
        37: "Vow",
        38: "Protection",
        39: "Nature",
        40: "Opinion",
        41: "Burden",
        42: "Vengeance",
        43: "Opportunity",
        44: "Faction",
        45: "Danger",
        46: "Corruption",
        47: "Freedom",
        48: "Debt",
        49: "Hate",
        50: "Possession",
        51: "Stranger",
        52: "Passage",
        53: "Land",
        54: "Creature",
        55: "Disease",
        56: "Advantage",
        57: "Blood",
        58: "Language",
        59: "Rumor",
        60: "Weakness",
        61: "Greed",
        62: "Family",
        63: "Resource",
        64: "Structure",
        65: "Dream",
        66: "Community",
        67: "War",
        68: "Portent",
        69: "Prize",
        70: "Destiny",
        71: "Momentum",
        72: "Power",
        73: "Memory",
        74: "Ruin",
        75: "Mysticism",
        76: "Rival",
        77: "Problem",
        78: "Idea",
        79: "Revenge",
        80: "Health",
        81: "Fellowship",
        82: "Enemy",
        83: "Religion",
        84: "Spirit",
        85: "Fame",
        86: "Desolation",
        87: "Strength",
        88: "Knowledge",
        89: "Truth",
        90: "Quest",
        91: "Pride",
        92: "Loss",
        93: "Law",
        94: "Path",
        95: "Warning",
        96: "Relationship",
        97: "Wealth",
        98: "Home",
        99: "Strategy",
        100: "Supply",
    },
    Region: {
        12: "Barrier Islands",
        24: "Ragged Coast",
        34: "Deep Wilds",
        46: "Flooded Lands",
        60: "Havens",
        72: "Hinterlands",
        84: "Tempest Hills",
        94: "Veiled Mountains",
        99: "Shattered Wastes",
        100: "Elsewhere",
    },
    Location: {
        1: "Hideout",
        2: "Ruin",
        3: "Mine",
        4: "Waste",
        5: "Mystical Site",
        6: "Path",
        7: "Outpost",
        8: "Wall",
        9: "Battlefield",
        10: "Hovel",
        11: "Spring",
        12: "Lair",
        13: "Fort",
        14: "Bridge",
        15: "Camp",
        16: "Cairn/Grave",
        18: "Caravan",
        20: "Waterfall",
        22: "Cave",
        24: "Swamp",
        26: "Fen",
        28: "Ravine",
        30: "Road",
        32: "Tree",
        34: "Pond",
        36: "Fields",
        38: "Marsh",
        40: "Steading",
        42: "Rapids",
        44: "Pass",
        46: "Trail",
        48: "Glade",
        50: "Plain",
        52: "Ridge",
        54: "Cliff",
        56: "Grove",
        58: "Village",
        60: "Moor",
        62: "Thicket",
        64: "River Ford",
        66: "Valley",
        68: "Bay/Fjord",
        70: "Foothills",
        72: "Lake",
        75: "River",
        79: "Forest",
        83: "Coast",
        88: "Hill",
        93: "Mountain",
        99: "Woods",
        100: "Anomaly",
    },
    "Costal Waters Location": {
        1: "Fleet",
        2: "Sargassum",
        3: "Flotsam",
        4: "Mystical Site",
        5: "Lair",
        10: "Wreck",
        15: "Harbor",
        23: "Ship",
        30: "Rocks",
        38: "Fjord",
        46: "Estuary",
        54: "Cove",
        62: "Bay",
        70: "Ice",
        85: "Island",
        99: "Open Water",
        100: "Anomaly",
    },
    "Location Descriptor": {
        2: "High",
        4: "Remote",
        6: "Exposed",
        8: "Small",
        10: "Broken",
        12: "Diverse",
        14: "Rough",
        16: "Dark",
        18: "Shadowy",
        20: "Contested",
        22: "Grim",
        24: "Wild",
        26: "Fertile",
        28: "Blocked",
        30: "Ancient",
        32: "Perilous",
        34: "Hidden",
        36: "Occupied",
        38: "Rich",
        40: "Big",
        42: "Savage",
        44: "Defended",
        46: "Withered",
        48: "Mystical",
        50: "Inaccessible",
        52: "Protected",
        54: "Abandoned",
        56: "Wide",
        58: "Foul",
        60: "Dead",
        62: "Ruined",
        64: "Barren",
        66: "Cold",
        68: "Blighted",
        70: "Low",
        72: "Beautiful",
        74: "Abundant",
        76: "Lush",
        78: "Flooded",
        80: "Empty",
        82: "Strange",
        84: "Corrupted",
        86: "Peaceful",
        88: "Forgotten",
        90: "Expansive",
        92: "Settled",
        94: "Dense",
        96: "Civilized",
        98: "Desolate",
        100: "Isolated",
    },
    "Settlement Name": {
        15: {
            10: "Highmount",
            20: "Brackwater",
            30: "Frostwood",
            40: "Redcrest",
            50: "Grimtree",
            60: "Stoneford",
            70: "Deepwater",
            80: "Whitefall",
            90: "Graycliff",
            100: "Three Rivers",
        },
        30: {
            10: "Whitebridge",
            20: "Lonefort",
            30: "Highcairn",
            40: "Redhall",
            50: "Darkwell",
            60: "Timberwall",
            70: "Stonetower",
            80: "Thornhall",
            90: "Cinderhome",
            100: "Fallowfield",
        },
        45: {
            10: "Ravencliff",
            20: "Bearmark",
            30: "Wolfcrag",
            40: "Eaglespire",
            50: "Wyvern's Rest",
            60: "Boarwood",
            70: "Foxhollow",
            80: "Elderwatch",
            90: "Elkfield",
            100: "Dragonshadow",
        },
        60: {
            10: "Swordbreak",
            20: "Fool's Fall",
            30: "Firstmeet",
            40: "Brokenhelm",
            50: "Mournhaunt",
            60: "Olgar's Stand",
            70: "Lostwater",
            80: "Rojirra's Lament",
            90: "Lastmarch",
            100: "Rockfall",
        },
        75: {
            10: "Abon",
            20: "Daveza",
            30: "Damula",
            40: "Essus",
            50: "Sina",
            60: "Kazeera",
            70: "Khazu",
            80: "Sova",
            90: "Nabuma",
            100: "Tiza",
        },
        90: {
            10: "Winterhome",
            20: "Windhaven",
            30: "Stormrest",
            40: "Bleakfrost",
            50: "Springtide",
            60: "Duskmoor",
            70: "Frostcrag",
            80: "Springbrook",
            90: "Icebreak",
            100: "Summersong",
        },
        100: {
            10: "A trade good (Ironhome)",
            20: "An Old World city (New Arkesh)",
            30: "A founder or famous settler (Kei's Hall)",
            40: "A god (Elisora)",
            50: "A historical item (Blackhelm)",
            60: "A firstborn race (Elfbrook)",
            70: "An elvish word or name (Nessana)",
            80: "A mythic belief or event (Ghostwalk)",
            90: "A positive term (Hope)",
            100: "A negative term (Forsaken)",
        },
    },
    "Quick Settlement Name": [
        {
            4: "Bleak",
            8: "Green",
            12: "Wolf",
            16: "Raven",
            20: "Gray",
            24: "Red",
            28: "Axe",
            32: "Great",
            36: "Wood",
            40: "Low",
            44: "White",
            48: "Storm",
            52: "Black",
            56: "Mourn",
            60: "New",
            64: "Stone",
            68: "Grim",
            72: "Lost",
            76: "High",
            80: "Rock",
            84: "Shield",
            88: "Sword",
            92: "Frost",
            96: "Thorn",
            100: "Long",
        },
        {
            4: "moor",
            8: "ford",
            12: "crag",
            16: "watch",
            20: "hope",
            24: "wood",
            28: "ridge",
            32: "stone",
            36: "haven",
            40: "falls",
            44: "river",
            48: "field",
            52: "hill",
            56: "bridge",
            60: "mark",
            64: "cairn",
            68: "land",
            72: "hall",
            76: "mount",
            80: "rock",
            84: "brook",
            88: "barrow",
            92: "stead",
            96: "home",
            100: "wick"
        },
    ],
    "Settlement Trouble": {
        2: "Outsiders rejected",
        4: "Dangerous discovery",
        6: "Dreadful omens",
        8: "Natural disaster",
        10: "Old wounds reopened",
        12: "Important object is lost",
        14: "Someone is captured",
        16: "Mysterious phenomenon",
        18: "Revolt against a leader",
        20: "Vengeful outcast",
        22: "Rival settlement",
        24: "Nature strikes back",
        26: "Someone is missing",
        28: "Production halts",
        30: "Mysterious murders",
        32: "Debt comes due",
        34: "Unjust leadership",
        36: "Disastrous accident",
        38: "In league with the enemy",
        40: "Raiders prey on the weak",
        42: "Cursed past",
        44: "An innocent is accused",
        46: "Corrupted by dark magic",
        48: "Isolated by brutal weather",
        50: "Provisions are scarce",
        52: "Sickness run amok",
        54: "Allies become enemies",
        56: "Attack is imminent",
        58: "Lost caravan",
        60: "Dark secret revealed",
        62: "Urgent expedition",
        64: "A leader falls",
        66: "Families in conflict",
        68: "Incompetent leadership",
        70: "Reckless warmongering",
        72: "Beast on the hunt",
        74: "Betrayed from within",
        76: "Broken truce",
        78: "Wrathful haunt",
        80: "Conflict with firstborn",
        82: "Trade route blocked",
        84: "In the crossfire",
        86: "Stranger causes discord",
        88: "Important event threatened",
        90: "Dangerous tradition",
        100: "Roll twice",
    },
    "Character Role": {
        2: "Criminal",
        4: "Healer",
        6: "Bandit",
        9: "Guide",
        12: "Performer",
        15: "Miner",
        18: "Mercenary",
        21: "Outcast",
        24: "Vagrant",
        27: "Forester",
        30: "Traveler",
        33: "Mystic",
        36: "Priest",
        39: "Sailor",
        42: "Pilgrim",
        45: "Thief",
        48: "Adventurer",
        51: "Forager",
        54: "Leader",
        58: "Guard",
        62: "Artisan",
        66: "Scout",
        70: "Herder",
        74: "Fisher",
        79: "Warrior",
        84: "Hunter",
        89: "Raider",
        94: "Trader",
        99: "Farmer",
        100: "Roll twice",
    },
    "Character Goal": {
        3: "Obtain an object",
        6: "Make an agreement",
        9: "Build a relationship",
        12: "Undermine a relationship",
        15: "Seek a truth",
        18: "Pay a debt",
        21: "Refute a falsehood",
        24: "Harm a rival",
        27: "Cure an ill",
        30: "Find a person",
        33: "Find a home",
        36: "Seize power",
        39: "Restore a relationship",
        42: "Create an item",
        45: "Travel to a place",
        48: "Secure provisions",
        51: "Rebel against power",
        54: "Collect a debt",
        57: "Protect a secret",
        60: "Spread faith",
        63: "Enrich themselves",
        66: "Protect a person",
        69: "Protect the status quo",
        72: "Advance status",
        75: "Defend a place",
        78: "Avenge a wrong",
        81: "Fulfill a duty",
        84: "Gain knowledge",
        87: "Prove worthiness",
        90: "Find redemption",
        92: "Escape from something",
        95: "Resolve a dispute",
        100: "Roll twice",
    },
    "Character Descriptor": {
        1: "Stoic",
        2: "Attractive",
        3: "Passive",
        4: "Aloof",
        5: "Affectionate",
        6: "Generous",
        7: "Smug",
        8: "Armed",
        9: "Clever",
        10: "Brave",
        11: "Ugly",
        12: "Sociable",
        13: "Doomed",
        14: "Connected",
        15: "Bold",
        16: "Jealous",
        17: "Angry",
        18: "Active",
        19: "Suspicious",
        20: "Hostile",
        21: "Hardhearted",
        22: "Successful",
        23: "Talented",
        24: "Experienced",
        25: "Deceitful",
        26: "Ambitious",
        27: "Aggressive",
        28: "Conceited",
        29: "Proud",
        30: "Stern",
        31: "Dependent",
        32: "Wary",
        33: "Strong",
        34: "Insightful",
        35: "Dangerous",
        36: "Quirky",
        37: "Cheery",
        38: "Disfigured",
        39: "Intolerant",
        40: "Skilled",
        41: "Stingy",
        42: "Timid",
        43: "Insensitive",
        44: "Wild",
        45: "Bitter",
        46: "Cunning",
        47: "Remorseful",
        48: "Kind",
        49: "Charming",
        50: "Oblivious",
        51: "Critical",
        52: "Cautious",
        53: "Resourceful",
        54: "Weary",
        55: "Wounded",
        56: "Anxious",
        57: "Powerful",
        58: "Athletic",
        59: "Driven",
        60: "Cruel",
        61: "Quiet",
        62: "Honest",
        63: "Infamous",
        64: "Dying",
        65: "Reclusive",
        66: "Artistic",
        67: "Disabled",
        68: "Confused",
        69: "Manipulative",
        70: "Relaxed",
        71: "Stealthy",
        72: "Confident",
        73: "Weak",
        74: "Friendly",
        75: "Wise",
        76: "Influential",
        77: "Young",
        78: "Adventurous",
        79: "Oppressed",
        80: "Vengeful",
        81: "Cooperative",
        82: "Armored",
        83: "Apathetic",
        84: "Determined",
        85: "Loyal",
        86: "Sick",
        87: "Religious",
        88: "Selfish",
        89: "Old",
        90: "Fervent",
        91: "Violent",
        92: "Agreeable",
        93: "Hot - tempered",
        94: "Stubborn",
        95: "Incompetent",
        96: "Greedy",
        97: "Cowardly",
        98: "Obsessed",
        99: "Careless",
        00: "Ironsworn",
    },
    "Ironlander Names": [
        {
            1: "Solana",
            2: "Keelan",
            3: "Cadigan",
            4: "Sola",
            5: "Kodroth",
            6: "Kione",
            7: "Katja",
            8: "Tio",
            9: "Artiga",
            10: "Eos",
            11: "Bastien",
            12: "Elli",
            13: "Maura",
            14: "Haleema",
            15: "Abella",
            16: "Morter",
            17: "Wulan",
            18: "Mai",
            19: "Farina",
            20: "Pearce",
            21: "Wynne",
            22: "Haf",
            23: "Aeddon",
            24: "Khinara",
            25: "Milla",
            26: "Nakata",
            27: "Kynan",
            28: "Kiah",
            29: "Jaggar",
            30: "Beca",
            31: "Ikram",
            32: "Melia",
            33: "Sidan",
            34: "Deshi",
            35: "Tessa",
            36: "Sibila",
            37: "Morien",
            38: "Mona",
            39: "Padma",
            40: "Avella",
            41: "Naila",
            42: "Lio",
            43: "Cera",
            44: "Ithela",
            45: "Zhan",
            46: "Kaivan",
            47: "Valeri",
            48: "Hirsham",
            49: "Pemba",
            50: "Edda",
            51: "Lestara",
            52: "Lago",
            53: "Elstan",
            54: "Saskia",
            55: "Kabeera",
            56: "Caldas",
            57: "Nisus",
            58: "Serene",
            59: "Chenda",
            60: "Themon",
            61: "Erin",
            62: "Alban",
            63: "Parcell",
            64: "Jelma",
            65: "Willa",
            66: "Nadira",
            67: "Gwen",
            68: "Amara",
            69: "Masias",
            70: "Kanno",
            71: "Razeena",
            72: "Mira",
            73: "Perella",
            74: "Myrick",
            75: "Qamar",
            76: "Kormak",
            77: "Zura",
            78: "Zanita",
            79: "Brynn",
            80: "Tegan",
            81: "Pendry",
            82: "Quinn",
            83: "Fanir",
            84: "Glain",
            85: "Emelyn",
            86: "Kendi",
            87: "Althus",
            88: "Leela",
            89: "Ishana",
            90: "Flint",
            91: "Delkash",
            92: "Nia",
            93: "Nan",
            94: "Keeara",
            95: "Katania",
            96: "Morell",
            97: "Temir",
            98: "Bas",
            99: "Sabine",
            00: "Tallus",
        },
        {
            1: " Segura",
            2: " Gethin",
            3: " Bataar",
            4: " Basira",
            5: " Joa",
            6: " Glynn",
            7: " Toran",
            8: " Arasen",
            9: " Kuron",
            10: " Griff",
            11: " Owena",
            12: " Adda",
            13: " Euros",
            14: " Kova",
            15: " Kara",
            16: " Morgan",
            17: " Nanda",
            18: " Tamara",
            19: " Asha",
            20: " Delos",
            21: " Torgan",
            22: " Makari",
            23: " Selva",
            24: " Kimura",
            25: " Rhian",
            26: " Tristan",
            27: " Siorra",
            28: " Sayer",
            29: " Cortina",
            30: " Vesna",
            31: " Kataka",
            32: " Keyshia",
            33: " Mila",
            34: " Lili",
            35: " Vigo",
            36: " Sadia",
            37: " Malik",
            38: " Dag",
            39: " Kuno",
            40: " Reva",
            41: " Kai",
            42: " Kalina",
            43: " Jihan",
            44: " Hennion",
            45: " Abram",
            46: " Aida",
            47: " Myrtle",
            48: " Nekun",
            49: " Menna",
            50: " Tahir",
            51: " Sarria",
            52: " Nakura",
            53: " Akiya",
            54: " Talan",
            55: " Mattick",
            56: " Okoth",
            57: " Khulan",
            58: " Verena",
            59: " Beltran",
            60: " Del",
            61: " Ranna",
            62: " Alina",
            63: " Muna",
            64: " Mura",
            65: " Torrens",
            66: " Yuda",
            67: " Nazmi",
            68: " Ghalen",
            69: " Sarda",
            70: " Shona",
            71: " Kalidas",
            72: " Wena",
            73: " Sendra",
            74: " Kori",
            75: " Setara",
            76: " Lucia",
            77: " Maya",
            78: " Reema",
            79: " Yorath",
            80: " Rhoddri",
            81: " Shekhar",
            82: " Servan",
            83: " Reese",
            84: " Kenrick",
            85: " Indirra",
            86: " Giliana",
            87: " Jebran",
            88: " Kotama",
            89: " Fara",
            90: " Katrin",
            91: " Namba",
            92: " Lona",
            93: " Taylah",
            94: " Kato",
            95: " Esra",
            96: " Eleri",
            97: " Irsia",
            98: " Kayu",
            99: " Bevan",
            00: " Chandra",
        }
    ],
    "Elf Names": {
        2: "Arsula",
        4: "Naidita",
        6: "Belesunna",
        8: "Vidarna",
        10: "Ninsunu",
        12: "Balathu",
        14: "Dorosi",
        16: "Gezera",
        18: "Zursan",
        20: "Seleeku",
        22: "Utamara",
        24: "Nebakay",
        26: "Dismashk",
        28: "Mitunu",
        30: "Atani",
        32: "Kinzura",
        34: "Sumula",
        36: "Ukames",
        38: "Ahmeshki",
        40: "Ilsit",
        42: "Mayatanay",
        44: "Etana",
        46: "Gamanna",
        48: "Nessana",
        50: "Uralar",
        52: "Tishetu",
        54: "Leucia",
        56: "Sutahe",
        58: "Dotani",
        60: "Uktannu",
        62: "Retenay",
        64: "Kendalanu",
        66: "Tahuta",
        68: "Mattissa",
        70: "Anatu",
        72: "Aralu",
        74: "Arakhi",
        76: "Ibrahem",
        78: "Sinosu",
        80: "Jemshida",
        82: "Visapni",
        84: "Hullata",
        86: "Sidura",
        88: "Kerihu",
        90: "Ereshki",
        92: "Cybela",
        94: "Anunna",
        96: "Otani",
        98: "Ditani",
        00: "Faraza",
    },
    "Giant Names": {
        4: "Chony",
        8: "Banda",
        12: "Jochu",
        16: "Kira",
        20: "Khatir",
        24: "Chaidu",
        28: "Atan",
        32: "Buandu",
        36: "Javyn",
        40: "Khashin",
        44: "Bayara",
        48: "Temura",
        52: "Kidha",
        56: "Kathos",
        60: "Tanua",
        64: "Bashtu",
        68: "Jaran",
        72: "Othos",
        76: "Khutan",
        80: "Otaan",
        84: "Martu",
        88: "Baku",
        92: "Tuban",
        96: "Qudan",
        00: "Denua",
    },
    "Varou Names": {
        4: "Vata",
        8: "Zora",
        12: "Jasna",
        16: "Charna",
        20: "Tana",
        24: "Soveen",
        28: "Radka",
        32: "Zlata",
        36: "Leesla",
        40: "Byna",
        44: "Meeka",
        48: "Iskra",
        52: "Jarek",
        56: "Darva",
        60: "Neda",
        64: "Keha",
        68: "Zhivka",
        72: "Kvata",
        76: "Staysa",
        80: "Evka",
        84: "Vuksha",
        88: "Muko",
        92: "Dreko",
        96: "Aleko",
        00: "Vojan",
    },
    "Troll Names": {
        4: "Rattle",
        8: "Scratch",
        12: "Wallow",
        16: "Groak",
        20: "Gimble",
        24: "Scar",
        28: "Cratch",
        32: "Creech",
        36: "Shush",
        40: "Glush",
        44: "Slar",
        48: "Gnash",
        52: "Stoad",
        56: "Grig",
        60: "Bleat",
        64: "Chortle",
        68: "Cluck",
        72: "Slith",
        76: "Mongo",
        80: "Creak",
        84: "Burble",
        88: "Vrusk",
        92: "Snuffle",
        96: "Leech",
        00: "Herk",
    },
    "Combat Action": {
        3: "Compel a surrender",
        6: "Coordinate with allies",
        9: "Gather reinforcements",
        13: "Seize something or someone",
        17: "Provoke a reckless response",
        21: "Intimidate or frighten",
        25: "Reveal a surprising truth",
        29: "Shift focus to someone or something else",
        33: "Destroy something, or render it useless",
        39: "Take a decisive action",
        45: "Reinforce defenses",
        52: "Ready an action",
        60: "Use the terrain to gain advantage",
        68: "Leverage the advantage of a weapon or ability",
        78: "Create an opportunity",
        89: "Attack with precision",
        99: "Attack with power",
        00: "Take a completely unexpected action",
    },
    "Mystic Backlash": {
        4: "Your ritual has the opposite affect",
        8: "You are sapped of strength",
        12: "Your friend, ally, or companion is adversely affected",
        16: "You destroy an important object",
        20: "You inadvertently summon a horror",
        24: "You collapse, and drift into a troubled sleep",
        28: "You undergo a physical torment which leaves its mark upon you",
        32: "You hear ghostly voices whispering of dark portents",
        36: "You are lost in shadow, and find yourself in another place without memory of how you got there",
        40: "You alert someone or something to your presence",
        44: "You are not yourself, and act against a friend, ally, or companion",
        48: "You affect or damage your surroundings, causing a disturbance or potential harm",
        52: "You waste resources",
        56: "You suffer the loss of a sense for several hours",
        60: "You lose your connection to magic for a day or so, and cannot perform rituals",
        64: "Your ritual affects the target in an unexpected and problematic way",
        68: "Your ritual reveals a surprising and troubling truth",
        72: "You are tempted by dark powers",
        76: "You see a troubling vision of your future",
        80: "You can't perform this ritual again until you acquire an important component",
        84: "You develop a strange fear or compulsion",
        88: "Your ritual causes creatures to exhibit strange or aggressive behavior",
        92: "You are tormented by an apparition from your past",
        96: "You are wracked with sudden sickness",
        00: "Roll twice more on this table. Both results occur. If they are the same result, make it worse.",
    },
    "Major Plot Twist": {
        5: "It was all a diversion",
        10: "A dark secret is revealed",
        15: "A trap is sprung",
        20: "An assumption is revealed to be false",
        25: "A secret alliance is revealed",
        30: "Your actions benefit an enemy",
        35: "Someone returns unexpectedly",
        40: "A more dangerous foe is revealed",
        45: "You and an enemy share a common goal",
        50: "A true identity is revealed",
        55: "You are betrayed by someone who was trusted",
        60: "You are too late",
        65: "The true enemy is revealed",
        70: "The enemy gains new allies",
        75: "A new danger appears",
        80: "Someone or something goes missing",
        85: "The truth of a relationship is revealed",
        90: "Two seemingly unrelated situations are shown to be connected",
        95: "Unexpected powers or abilities are revealed",
        00: "Roll twice more on this table. Both results occur. If they are the same result, make it more dramatic.",
    },
    "Challenge Rank": {
        20: "Troublesome",
        55: "Dangerous",
        80: "Formidable",
        93: "Extreme",
        00: "Epic",
    },
}